# This is a basic workflow to help you get started with Actions

name: Clone Reepository and Markdown

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "Testapplications_for_Ufni"
  push:
    branches: [ "Testapplications_for_Uni" ]
  pull_request:
    branches: [ "Testapplications_for_Uni" ]
    
permissions:
    contents: write

    
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
    
  clone_rds:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        run: git clone https://github.com/Soroush9978/rds-ng ./reposit01
      - name: Say something
        run: |
         ls -ltrh ./reposit01 > content.txt
      - name: Say something
        run: |
          cat content.txt
      - name: install python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11.0  # Choose the Python version you need
      - name: Install Pydoc-Markdown
        run: pip install pydoc-markdown
      - name: Run Pydoc-Markdown
        run: pydoc-markdown --help
      - name: use pydoc
        run: pydoc-markdown -I ./repsit01
      - name: install node
        uses: actions/setup-node@v2
        with:
          node-version: 18
          
          
      - name: Change Directory
        run: |
          node -v
          cd ./reposit01/docs
          ls -ltrh
          npm ci
          npm run build
      - name: Pushes to another repository
        uses: cpina/github-action-push-to-another-repository@main
        env: 
            API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
              source-directory: 'docs/build'
              destination-github-username: 'Soroush9978'
              destination-repository-name: 'rnawrozi.github.io'
              user-email: pasandideh91@gmail.com
              target-branch: master
      
          
 
      

      
          
          
  
        

        
    
  
